config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :badge_tasks
  resources :badges
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badge_tasks, foreign_key: :task_id
  # has_many :tasks, through: :badge_tasks
  has_and_belongs_to_many :tasks
end

app/models/badge_task.rb
class BadgeTask < ApplicationRecord
  has_one :badge, foreign_key: :id
  has_one :task, foreign_key: :id
end

app/models/course_log.rb
class CourseLog < ApplicationRecord
  actable as: :course_log
  acts_as :log, as: :log
end

app/models/log.rb
class Log < ApplicationRecord
  actable as: :log
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :badge_tasks, foreign_key: :badge_id
  # has_many :badges, through: :badge_tasks

  has_and_belongs_to_many :badges
end

app/models/task_log.rb
class TaskLog < ApplicationRecord
  acts_as :course_log, as: :course_log
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/badge_tasks_controller.rb
class BadgeTasksController < ApplicationController
  before_action :set_badge_task, only: [:show, :edit, :update, :destroy]

  # GET /badge_tasks
  # GET /badge_tasks.json
  def index
    @badge_tasks = BadgeTask.all
  end

  # GET /badge_tasks/1
  # GET /badge_tasks/1.json
  def show
  end

  # GET /badge_tasks/new
  def new
    @badge_task = BadgeTask.new
  end

  # GET /badge_tasks/1/edit
  def edit
  end

  # POST /badge_tasks
  # POST /badge_tasks.json
  def create
    @badge_task = BadgeTask.new(badge_task_params)

    respond_to do |format|
      if @badge_task.save
        format.html { redirect_to @badge_task, notice: 'Badge task was successfully created.' }
        format.json { render :show, status: :created, location: @badge_task }
      else
        format.html { render :new }
        format.json { render json: @badge_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badge_tasks/1
  # PATCH/PUT /badge_tasks/1.json
  def update
    respond_to do |format|
      if @badge_task.update(badge_task_params)
        format.html { redirect_to @badge_task, notice: 'Badge task was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge_task }
      else
        format.html { render :edit }
        format.json { render json: @badge_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badge_tasks/1
  # DELETE /badge_tasks/1.json
  def destroy
    @badge_task.destroy
    respond_to do |format|
      format.html { redirect_to badge_tasks_url, notice: 'Badge task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge_task
      @badge_task = BadgeTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_task_params
      params.require(:badge_task).permit(:name, :task_id, :badge_id)
    end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, badge_ids:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badge_tasks_helper.rb
module BadgeTasksHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/badge_tasks/_form.html.erb
<%= form_for(badge_task) do |f| %>
  <% if badge_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(badge_task.errors.count, "error") %> prohibited this badge_task from being saved:</h2>

      <ul>
      <% badge_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :task_id %>
    <%= f.number_field :task_id %>
  </div>

  <div class="field">
    <%= f.label :badge_id %>
    <%= f.number_field :badge_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badge_tasks/edit.html.erb
<h1>Editing Badge Task</h1>

<%= render 'form', badge_task: @badge_task %>

<%= link_to 'Show', @badge_task %> |
<%= link_to 'Back', badge_tasks_path %>

app/views/badge_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Badge Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Task</th>
      <th>Badge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @badge_tasks.each do |badge_task| %>
      <tr>
        <td><%= badge_task.name %></td>
        <td><%= badge_task.task_id %></td>
        <td><%= badge_task.badge_id %></td>
        <td><%= link_to 'Show', badge_task %></td>
        <td><%= link_to 'Edit', edit_badge_task_path(badge_task) %></td>
        <td><%= link_to 'Destroy', badge_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge Task', new_badge_task_path %>

app/views/badge_tasks/new.html.erb
<h1>New Badge Task</h1>

<%= render 'form', badge_task: @badge_task %>

<%= link_to 'Back', badge_tasks_path %>

app/views/badge_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @badge_task.name %>
</p>

<p>
  <strong>Task:</strong>
  <%= @badge_task.task_id %>
</p>

<p>
  <strong>Badge:</strong>
  <%= @badge_task.badge_id %>
</p>

<%= link_to 'Edit', edit_badge_task_path(@badge_task) %> |
<%= link_to 'Back', badge_tasks_path %>

app/views/badges/_form.html.erb
<%= form_for(badge) do |f| %>
  <% if badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% badge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Badges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.name %></td>
        <td><%= link_to 'Show', badge %></td>
        <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @badge.name %>
</p>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.collection_check_boxes :badge_ids, Badge.all, :id, :name, {}, {:multiple => true} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>